name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before Checkout
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1 
      - name: List Files Adfter Checkout
        run: |
          pwd
          ls -a 
      - name: Simple Javascript Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Henry
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
