name: Actions Workflow

on: [push]

jobs:
  build-and-copy:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before Checkout
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1 
      - name: List Files After Checkout
        run: |
          pwd
          ls -a 
      - name: Zip it
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r test.zip test.yml
      - name: List Files After Zip
        run: |
          pwd
          ls -a 
      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Copy to S3
        run: aws s3 cp test.zip s3://actionscodecopy/test.zip
         